### ISSUE TITLE
Boto 1.16.0 not compatible with ssm lookup

### ISSUE THREAD

**Issue by stayman** [ansible-collections/amazon.aws#175] opened 2020-10-20 20:42 UTC
##### SUMMARY
SSM lookup fails when using boto3 1.16.0

When attempting a lookup via boto3 1.15.0 everything works successfully

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ssm lookup

##### ANSIBLE VERSION

```sh
ansible 2.9.14
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

There is no output.

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  become: true
  pre_tasks:
    - name: install boto3
      pip:
        name: boto3

    - name: get instance metadata
      ec2_metadata_facts:

    - name: retrieve ssm parameter
      set_fact:
        param: "{{ lookup('aws_ssm', ssm_path, region=ansible_ec2_placement_region) }}"
```

##### EXPECTED RESULTS

SSM parameter successfully retrieved

##### ACTUAL RESULTS

SSM errors saying boto3 and botocore are required

please note this is being run via `cloudinit`
```sh
TASK [retrieve ssm parameter] **************************************************
task path: /run/ansible/frontend/site.yml:18
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'aws_ssm'. Error was a <class 'ansible.errors.AnsibleError'>, original message: botocore and boto3 are required for aws_ssm lookup."
}
```

**Comment by gravesm** [comment] 2021-01-05 20:43
@stayman I'm unable to reproduce this error using the same ansible and boto3 versions you have listed here. Can you confirm this is still an issue? If so, could you provide the debug output for the ansible playbook command (`-vvv`)?

**Comment by tremble** [comment] 2021-01-07 12:49
The error you're seeing is only caused by an import failure and not by any kind of version checking.  On RHEL I sometimes see this if there are multiple Python environments, or python venvs, and the module is loaded by doesn't include it.

Telling Ansible to explicitly use the version of python from the environment can help:

```
ansible_python_interpreter: "/usr/bin/env python"
```

See also https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

**Comment by goneri** [comment] 2021-01-22 20:06
Closing as per @tremble answer.

**Closed by goneri** 2021-01-22 20:06 UTC
Labels: bug, priority/medium, python3
