### ISSUE TITLE
Can't pretty print hostvars

### ISSUE THREAD

**Issue by kenwdelong** [ansible-collections/amazon.aws#190] opened 2020-11-04 21:56 UTC
##### SUMMARY

The EC2 inventory plugin includes a tzinfo() call in hostvars which prevent it from being pretty printed. [https://github.com/ansible/ansible/issues/72484](https://github.com/ansible/ansible/issues/72484)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aws_ec2

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/kdelong/hatch-devops/ansible/ansible.cfg
  configured module search path = [u'/home/kdelong/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Aug 27 2020, 21:22:52) [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/kdelong/hatch-devops/ansible/ansible.cfg) = [u'/home/kdelong/hatch-devops/ansible/inventory']
DEFAULT_PRIVATE_KEY_FILE(/home/kdelong/hatch-devops/ansible/ansible.cfg) = /home/kdelong/.ssh/hatch_ops_id_rsa
DEFAULT_REMOTE_USER(/home/kdelong/hatch-devops/ansible/ansible.cfg) = hatch_ops
HOST_KEY_CHECKING(/home/kdelong/hatch-devops/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/kdelong/hatch-devops/ansible/ansible.cfg) = /usr/bin/python
RETRY_FILES_ENABLED(/home/kdelong/hatch-devops/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/kdelong/hatch-devops/ansible/ansible.cfg) = ignore

```

##### OS / ENVIRONMENT

Amazon Linux 2

##### STEPS TO REPRODUCE

```yaml
---
- hosts: master
  become: True
  become_user: root
  gather_facts: Yes
  tasks:
    - debug: 
        var: hostvars[inventory_hostname]
    - debug: 
        var: hostvars[inventory_hostname] | to_nice_json
```

##### EXPECTED RESULTS

Pretty printed JSON

##### ACTUAL RESULTS

The JSON is escaped.  See attached file
[fullOutput.zip](https://github.com/ansible-collections/amazon.aws/files/5490711/fullOutput.zip)

```paste below

```
Issue referred from main Ansible project. See [https://github.com/ansible/ansible/issues/72484](https://github.com/ansible/ansible/issues/72484)

**Comment by goneri** [comment] 2021-01-06 19:29
Hi @kenwdelong,

I cannot reproduce the problem with both Python 2.7 and 3.8. This is the output of `pip freeze` in my py27 virtual environment:

```
ansible==2.10.5
ansible-base==2.10.4
boto==2.49.0
boto3==1.16.49
botocore==1.19.49
cffi==1.14.4
cryptography==3.3.1
enum34==1.1.10
futures==3.3.0
ipaddress==1.0.23
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
packaging==20.8
pycparser==2.20
pyparsing==2.4.7
python-dateutil==2.8.1
PyYAML==5.3.1
s3transfer==0.3.3
six==1.15.0
urllib3==1.26.2
```

I suspect you may be using an older version of one of these packages. Can you please compare with your set-up?

waiting_on_contributor

**Comment by kenwdelong** [comment] 2021-01-06 20:11
It seems like many of my packages are older. Are these all dependencies of ansible?

I actually use a playbook to upgrade ansible:

```    - name: upgrade ansible
      pip:
        name:
          - ansible
        state: latest
```

Should I actually be using `name: *`, or will upgrading Ansible bring in all its latest dependencies (which is what I assumed).

**Comment by goneri** [comment] 2021-01-06 20:31
This is more a question for IRC or the mailing list (https://docs.ansible.com/ansible/latest/community/communication.html). If you want to be sure you are up to date, I would suggest you can prepare a fresh virtual environment. Also, I see you still use Python 2.7, it may be a good idea to try Python 3.6 or greater.

**Comment by goneri** [comment] 2021-01-06 20:42
@kenwdelong, I close the issue since I cannot reproduce it, feel free to reopen it if you think this was a mistake.

**Closed by goneri** 2021-01-06 20:42 UTC
Labels: inventory, needs_verified, priority/low
