### ISSUE TITLE
Support for Amazon Managed Prometheus

### ISSUE THREAD

**Issue by AnakinPt** [ansible-collections/amazon.aws#554] opened 2021-10-28 15:46 UTC
### Summary

With the launch of AMP I would like to use Ansible to update my AMP alerts and rules.

### Issue Type

Feature Idea

### Component Name

prometheus

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by gravesm** [comment] 2021-11-02 18:40
@AnakinPt thank you for submitting this feature request.

**Comment by alinabuzachis** [comment] 2022-01-11 16:25
Closed because duplicate of https://github.com/ansible-collections/community.aws/issues/855.

**Closed by alinabuzachis** 2022-01-11 16:25 UTC
Labels: waiting_on_contributor, feature
