### ISSUE TITLE
aws_ec2 inventory plugin includes hosts in parent_group that are found in boto different profile/config

### ISSUE THREAD

**Issue by invizus** [ansible-collections/amazon.aws#59] opened 2020-05-28 19:38 UTC
##### SUMMARY
Using aws_ec2 inventory plugin. I have multiple AWS accounts, some instances in each of those accounts perform same functions, i.e. management servers. 

Example: 2 accounts are Prod and QA. Each has a management instance, but different web app instances. 

Goal: I want to group instances by account(profile) and by purpose which I define in tags.

Problem: plugin will not group instances by parent group properly, it will mix them across all profiles. Each parent group will have all instances that match tag in `keyed_groups`.

Workaround: add prefix

Why workaround is not accepted solution: I want to have _group_vars/management.yml_ variable file, in which I will configure variables for all management instances, and have _group_vars/aws_qa.yml_ which will contain variables for all instances from QA account.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ec2 inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/user/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/ansible/ansible.cfg) = -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey,keyboard-interactive -o ControlMaster=auto -o ControlPersist=600s
CACHE_PLUGIN(/home/user/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/ansible/ansible.cfg) = cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/ansible/ansible.cfg) = 86400
DEFAULT_ACTION_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/home/user/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/home/user/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/ansible/ansible.cfg) = [u'/home/user/ansible/inventory']
DEFAULT_LOG_PATH(/home/user/ansible/ansible.cfg) = /home/user/ansible/ansible_user.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/home/user/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/home/user/ansible/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/home/user/ansible/ansible.cfg) = 15
DEFAULT_TIMEOUT(/home/user/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/user/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING(/home/user/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/user/ansible/ansible.cfg) = [u'aws_ec2', u'ini', u'yaml']
```

##### OS / ENVIRONMENT
My OS is Ubuntu 18.04
Working with AWS EC2 via API using AWS EC2 inventory plugin.

##### STEPS TO REPRODUCE
inventory prod:
```yaml
plugin: aws_ec2
boto_profile: profile-prod
keyed_groups:
  - key: tags.Name
    separator: ""
    parent_group: owner
  - key: tags.environment
    separator: ""
    parent_group: aws_prod
filters:
  tag:environment: management
hostnames:
  - dns-name
  - private-dns-name
```
inventory QA:
```yaml
plugin: aws_ec2
boto_profile: profile-qa
keyed_groups:
  - key: tags.Name
    separator: ""
    parent_group: owner
  - key: tags.environment
    separator: ""
    parent_group: aws_qa
filters:
  tag:environment: management
hostnames:
  - dns-name
  - private-dns-name
```
Also, AWS API credentials in `~/.aws/credentials`

`ansible-inventory --graph`

##### EXPECTED RESULTS
```
@all:
  |--@aws_prod:
  |  |--@management:
  |  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
  |--@aws_ec2:
  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
  |  |--ec2-2-3-4-6.us-west-2.compute.amazonaws.com
  |  |--ec2-2-3-4-7.us-west-2.compute.amazonaws.com
  |--@aws_qa:
  |  |--@management:
  |  |  |--ec2-2-3-4-6.us-west-2.compute.amazonaws.com
  |  |  |--ec2-2-3-4-7.us-west-2.compute.amazonaws.com
  |--@ungrouped:
  |--@owner:
  |  |--@user1:
  |  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |--@user2:
  |  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
```
##### ACTUAL RESULTS
```
@all:
  |--@aws_prod:
  |  |--@management:
  |  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
  |  |  |--ec2-2-3-4-6.us-west-2.compute.amazonaws.com
  |  |  |--ec2-2-3-4-7.us-west-2.compute.amazonaws.com
  |--@aws_ec2:
  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
  |  |--ec2-2-3-4-6.us-west-2.compute.amazonaws.com
  |  |--ec2-2-3-4-7.us-west-2.compute.amazonaws.com
  |--@aws_qa:
  |  |--@management:
  |  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
  |  |  |--ec2-2-3-4-6.us-west-2.compute.amazonaws.com
  |  |  |--ec2-2-3-4-7.us-west-2.compute.amazonaws.com
  |--@ungrouped:
  |--@owner:
  |  |--@user1:
  |  |  |--ec2-1-2-3-4.us-west-1.compute.amazonaws.com
  |  |--@user2:
  |  |  |--ec2-1-2-3-5.us-west-1.compute.amazonaws.com
```
```

**Comment by flowerysong** [comment] 2020-06-03 14:04
This is not a bug.

In Ansible group names are a flat namespace. You cannot have separate groups with the same name, regardless of what inventory source you use. You need to either give your groups distinct names (e.g. `management_qa` and `management_prod`) or avoid nesting them (put all of the QA hosts in `aws_qa`, all of the management hosts in `management`, and don't define a relationship between the two groups.)

**Comment by goneri** [comment] 2020-12-09 13:24
Thank you @flowerysong the answer, I close the issue. @invizus, please use the user mailing if you've got any additional questions.

**Closed by goneri** 2020-12-09 13:24 UTC
Labels: affects_2.10, bug, needs_triage
